#!/bin/bash

defaultoutputdir="../modescan/modes"

#--------------------------------------------------
#                Print help page
#--------------------------------------------------
function MAN {
cat << EOF

Synopsis:  ${0##*/} {h} inputfile [outputdir]

Description:
    Read a formcheckfile and extract its
        - minimum geometry       > outputdirectory/coords
        - normal frequency modes > outputdirectory/mode_\d\{2,\}
        - atom masses            > outputdirectory/masses
        - harmonic frequencies   > outputdirectory/freq_harmonic
    and output a paste of minimum coordinates and masses for a quick check

    The defualt values are:
        Output Directory = $defaultoutputdir

EOF
}
export -f MAN

for i in $@; do if [[ $i == '-h' ]]; then MAN; exit 0; fi; done
if [ $# -eq 0 ]; then MAN; exit 0; fi

#--------------------------------------------------
#             Actual start of script
#--------------------------------------------------
inputfile="$1"
# set standard outputdir to $defaultoutputdir
#   if a second argument is given use that instead
outputdir="${2:-$defaultoutputdir}"

if [ ! -e "$inputfile" ]; then printf "Please specify a valid inputfile\n"; MAN; exit 1; fi
if [ ! -d "$outputdir" ]; then mkdir -p "$outputdir"; fi

gaussianbohr=0.5291772085936
n_atoms=$(grep atoms $inputfile | awk '{print $5}')

#--------------------------------------------------
#               Generate masses file
#--------------------------------------------------
sed '/Vib-AtMass/,/Vib-E2/!d; s/^\s\+//' $inputfile | head -n-1 | tail -n+2 | awk '{for(i = 1; i <= NF; ++i){print $i}}' > $outputdir/masses

#--------------------------------------------------
#               Generate Atom map
#--------------------------------------------------
sed '/Atomic numbers/,/Nuclear charges/!d' $inputfile | head -n-1 | tail -n+2 | tr -d '\n' | sed "s/\s*\b\([[:digit:]]\+\)\b\s*/\1\n/g" > $outputdir/atommap

# Make atommap useful
sed -i "s/\b1\b/H/" $outputdir/atommap
sed -i "s/\b6\b/C/" $outputdir/atommap
sed -i "s/\b7\b/N/" $outputdir/atommap
sed -i "s/\b8\b/O/" $outputdir/atommap


#--------------------------------------------------
#  Check line numbers of atommap and masses files
#--------------------------------------------------
n_atmass=$(awk 'END{print NR}' $outputdir/masses)
n_at_map=$(awk 'END{print NR}' $outputdir/atommap)
if [ $n_atoms -ne $n_atmass -o $n_atoms -ne $n_at_map ]; then
    printf "\nERROR: Number of atoms ($n_atoms) not equal to "
    printf "number of atom masses ($n_atmass) and atom map ($n_at_map)\n"
    printf "       Aborting...\n\n"
    exit 2
fi

#--------------------------------------------------
#               Minimum coordinates
#--------------------------------------------------
sed '/Current cartesian coordinates/,/Force Field/!d' $inputfile | head -n-1 | tail -n+2 |
    awk '{
        for(i = 1; i <= NF; ++i){
            printf "\t% .8le", $i*'$gaussianbohr';
            if( (i + 5*(NR-1)) % 3 == 0){
                printf "\n"
            }
        }
    }' > $outputdir/coords

paste -d\  $outputdir/atommap $outputdir/coords > $outputdir/tmp
mv $outputdir/tmp $outputdir/coords
rm $outputdir/atommap

printf "Used geometry and masses for frequency calculation:\n"
paste $outputdir/coords $outputdir/masses | awk '{if(NF == 5){print $0 }else{ print $0; exit 7 }}'

if [ $? -ne 0 ]; then
    printf "\nERROR: Line count not equal for all columns\n       Aborting...\n\n"
    exit 3
fi

#--------------------------------------------------
#                   Normal modes
#--------------------------------------------------
sed '/Vib-Modes/,$ !d' $inputfile | tail -n+2 |
    awk '{
        for(i = 1; i <= NF; ++i){
            printf "\t% .8le", $i
            if( (i + 5*(NR-1)) % 3 == 0){
                printf "\n"
            }
        }
    }' |
    awk '{
        if(NR % '$n_atoms' == 1){
            file = "'$outputdir/'mode_" sprintf("%02d", NR/'$n_atoms' + 1)
        }
        print > file
    }'

count=0;
for i in $outputdir/mode_*; do
    count=$((count + 1))
    paste $i $outputdir/masses > tmp
    mv tmp $i
done

#--------------------------------------------------
#             Harmonic Frequency File
#       (requires count from Normal Modes)
#--------------------------------------------------
sed '/Vib-E2/,/Vib-Modes/!d' $inputfile | head -n-1 | tail -n+2 | awk '
    BEGIN{
        j=0
    }{
        for(i = 1; i <= NF; ++i){
            j += 1;
            printf "% 4.0lf    %12.6lf\n", j, $i;
            if('$count' <= j){
                exit
            }
        }
    }' > $outputdir/freq_harmonic
